# data
notes: "Meta Pd V1, gelu, 300"

# training parameters
gamma: 0.95
tau: 0.95
policy_htype: gelu
policy_hsize: [2048, 1024, 512]
policy_optimizer: "Adam"
policy_lr: 5.e-5
policy_momentum: 0.0
policy_weightdecay: 0.0
value_htype: gelu
value_hsize: [2048, 1024, 512]
value_optimizer: "Adam"
value_lr: 3.e-4
value_momentum: 0.0
value_weightdecay: 0.0
clip_epsilon: 0.2
min_batch_size: 50000
mini_batch_size: 50000
num_optim_epoch: 10
log_std: -2.3
fix_std: true
num_epoch: 25000
seed: 1
save_n_epochs: 100
reward_id: "world_rfc_implicit"
obs_type: "full"
actor_type: "gauss"
num_primitive: 8
action_v: 1
obs_v: 2
reactive_v: 0
reactive_rate: 0.3
sampling_temp: 0.2
rfc_decay: false
rfc_decay_max: 10000

reward_weights:
  w_p: 0.3
  w_v: 0.1
  w_e: 0.45
  w_c: 0.1
  w_vf: 0.05
  k_p: 2.0
  k_v: 0.005
  k_e: 5.0
  k_c: 100.0
  k_vf: 1.0

data_specs:
  dataset_name: amass
  file_path: sample_data/amass_copycat_train_singles.pkl
  # file_path: sample_data/amass_copycat_test_singles.pkl
  # file_path: sample_data/amass_copycat_take3_test.pkl
  state_file_path: sample_data/amass_copycat_take3_states_obs_v2.pkl
  # state_file_path: sample_data/amass_copycat_take3_test_states.pkl
  # test_file_path: sample_data/amass_copycat_take2.pkl
  # test_file_path: sample_data/amass_copycat_take2_test.pkl
  # test_file_path: sample_data/amass_copycat_take2_test_singles.pkl
  # test_file_path: sample_data/relive_mocap_qpos_grad.pkl
  # test_file_path: sample_data/amass_copycat_take4.pkl
  # test_file_path: sample_data/egopose_mocap_qpos.pkl
  # test_file_path: sample_data/relive_ar_qpos.pkl
  # test_file_path: sample_data/relive_wild_qpos.pkl
  # test_file_path: sample_data/relive_ar_qpos.pkl
  # test_file_path: sample_data/standing_neutral_qpos.pkl
  # test_file_path: sample_data/relive_third_qpos.pkl
  # test_file_path: "/hdd/zen/data/copycat/seqs/AIST++/aist_qpos.pkl"

  neutral_path: sample_data/standing_neutral.pkl
  flip_cnd: 0
  has_smpl_root: true
  traj_dim: 144
  t_min: 15
  t_max: 300
  nc: 2
  load_class: -1
  adaptive_iter: 200
  root_dim: 6
  flip_time: false
  mode: "all"
  base_rot: [0.7071, 0.7071, 0.0, 0.0]

# expert and environment
meta_pd: true
meta_pd_joint: false
mujoco_model: humanoid_smpl_neutral_mesh
vis_model: humanoid_smpl_neutral_mesh_vis

env_episode_len: 100000
env_term_body: "body"
env_expert_trail_steps: 0
obs_coord: "root"
obs_phase: false

# RFC parameters
residual_force: true
residual_force_scale: 300.0
residual_force_mode: implicit
has_shape: false
# other joint and body parameters
robot:
  mesh: True
  body_params:
    {}
    # offset:
    #   type: 'xyz'
    #   lb: [-0.2, -0.2, -0.2]
    #   ub: [0.2, 0.2, 0.2]
    #   rel: true

  joint_params: {}

  geom_params:
    size:
      lb: 0.01
      ub: 0.3

  actuator_params: # {}
    gear:
      lb: 0
      ub: 3
